version: '3.3'
services:
        db:
                build: ./mysql/
                restart: always
        wordpress:
                depends_on:
                        - db
                image: wordpress
                restart: always
                ports:
                        - "8080:80"
                environment: 
                        WORDPRESS_DB_HOST: db
                        WORDPRESS_DB_USER: wp
                        WORDPRESS_DB_PASSWORD: wp
                        WORDPRESS_DB_NAME: wp
                volumes:
                        - ./wp:/var/www/html
                         

