version: '3.3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
